[package]
name = "bs-frontend"
version = "0.1.0"
authors = ["PepcyCh <pepsich86@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.40"
serde_json = "1.0.64"
# yew = { git = "https://github.com/yewstack/yew", branch = "master" }
# yew-router = { git = "https://github.com/yewstack/yew/tree/master/packages/yew-router", branch = "master" }
yew = "0.17.4"
yew-router = "0.14.0"
wasm-bindgen = "0.2.67"
regex = "1.4.6"
lazy_static = "1.4.0"

common = { path = "../common" }